# Generated by Django 2.2.2 on 2019-10-01 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('more_info', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Architecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Toolchain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, max_length=255)),
                ('displayed_name', models.TextField()),
                ('auto_loaded', models.BooleanField(default=False)),
                ('hide', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255)),
                ('module_load', models.TextField(blank=True)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bear_applications.Application')),
            ],
            options={
                'unique_together': {('application', 'version')},
            },
        ),
        migrations.CreateModel(
            name='CurrentVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bear_applications.Application')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bear_applications.Version')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bear_applications.Origin'),
        ),
        migrations.CreateModel(
            name='ParagraphData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(unique=True, max_length=255)),
                ('content', models.TextField()),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bear_applications.Version')),
            ],
            options={
                'unique_together': {('version', 'header')},
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('architecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bear_applications.Architecture')),
                ('toolchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bear_applications.Toolchain')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bear_applications.Version')),
            ],
            options={
                'unique_together': {('version', 'toolchain', 'architecture')},
            },
        ),
    ]
