# Generated by Django 2.2.2 on 2019-10-02 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bear_applications', '0002_auto_20191002_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='architecture',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='bear_applications.Architecture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='version',
            name='toolchain',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='bear_applications.Toolchain'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
