# Generated by Django 2.2.2 on 2019-10-03 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bear_applications', '0004_auto_20191002_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='version',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='bear_applications.Version'),
            preserve_default=False,
        ),
    ]
