# Generated by Django 2.2.2 on 2019-10-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bear_applications', '0006_auto_20191007_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='reason_to_hide',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='reason_to_hide',
            field=models.TextField(null=True),
        ),
    ]
