# Generated by Django 2.2.2 on 2019-10-08 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bear_applications', '0007_auto_20191008_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraphdata',
            name='added_by',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='paragraphdata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
