# Generated by Django 2.2.2 on 2019-10-09 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bear_applications', '0008_auto_20191008_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paragraphdata',
            options={'ordering': ['created']},
        ),
    ]
