# Generated by Django 2.2.2 on 2019-10-15 08:49

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):
    # the model sets the order based on this, so the migration should as well
    if settings.WEBSITE_SITE_CONFIG['BAV_ORDER'] == 'asc':
        bav_order = 'displayed_name'
    else:
        bav_order = '-displayed_name'

    dependencies = [
        ('bear_applications', '0009_auto_20191009_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='architecture',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='bearappsversion',
            options={'ordering': [bav_order]},
        ),
    ]
