# Generated by Django 2.2.2 on 2019-10-15 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bear_applications', '0010_auto_20191015_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-bearappsversion__displayed_name', 'architecture__name']},
        ),
    ]
