# Generated by Django 2.2.8 on 2020-02-10 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bear_applications', '0011_auto_20191015_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='origin',
        ),
        migrations.DeleteModel(
            name='Origin',
        ),
    ]
