# Generated by Django 2.2.8 on 2020-02-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bear_applications', '0012_auto_20200210_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='bearappsversion',
            name='is_deprecated',
            field=models.BooleanField(default=False),
        ),
    ]
