# Generated by Django 2.2.8 on 2020-02-11 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bear_applications', '0013_bearappsversion_is_deprecated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bearappsversion',
            old_name='is_deprecated',
            new_name='deprecated',
        ),
        migrations.RenameField(
            model_name='bearappsversion',
            old_name='hide',
            new_name='hidden',
        ),
    ]
