# Generated by Django 2.2.12 on 2020-04-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bear_applications', '0015_architecture_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='dependencies',
            field=models.ManyToManyField(related_name='requires', to='bear_applications.Version'),
        ),
    ]
