# Generated by Django 2.2.12 on 2020-04-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bear_applications', '0016_version_dependencies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['-app_sort_order', '-version']},
        ),
        migrations.AddField(
            model_name='version',
            name='app_sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
