# Generated by Django 3.0.9 on 2020-10-06 17:06

from django.db import migrations, models

def copy_name_to_displayed_name(apps, schema_editor):
    Architecture = apps.get_model('bear_applications', 'architecture')
    db_alias = schema_editor.connection.alias
    from django.db.models import F
    Architecture.objects.using(db_alias).all().update(
        displayed_name=F('name')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('bear_applications', '0017_auto_20200430_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='architecture',
            name='displayed_name',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.RunPython(copy_name_to_displayed_name),
    ]
