# Generated by Django 3.2.5 on 2021-07-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bear_applications', '0020_auto_20210514_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraphdata',
            name='header',
            field=models.CharField(max_length=255),
        ),
    ]
