# Generated by Django 3.2.12 on 2022-02-11 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bear_applications', '0021_alter_paragraphdata_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('architecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bear_applications.architecture')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'architecture')},
            },
        ),
    ]
